send-text:
  handler: src/functions/send-text/sms.handler
  timeout: 29
  memorySize: 128
  reservedConcurrency: 5
  events:
    - http:
        path: /send-text
        method: POST

# TODO: Add SNS:Publish permissions to send-text

dispatch:
  handler: src/functions/send-text/sqs.handler
  events:
    - sqs:
        arn:
          Fn::GetAtt:
            - SendTextSmsQueue
            - Arn
