ApiGatewayRestApi:
  Type: AWS::ApiGateway::RestApi
  Properties:
    Name: ${self:custom.stackname}
    Description: API Gateway ${self:custom.stackname}

# ApiGatewayResourceSendText:
#   Type: AWS::ApiGateway::Resource
#   Properties:
#     RestApiId: { Ref: 'ApiGatewayRestApi' }
#     ParentId: { Fn::GetAtt: 'ApiGatewayRestApi.RootResourceId' }
#     PathPart: send-text

SendTextSnsTopic:
  Type: AWS::SNS::Topic
  Properties:
    TopicName: SendTextSnsTopic

SendTextSmsQueue:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: SendTextSmsQueue
    
SendTextSmsQueueSqsPolicy:
  Type: AWS::SQS::QueuePolicy
  Properties:
    PolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Sid: allow-sns-messages
          Effect: Allow
          Principal: "*"
          Resource: !GetAtt
            - SendTextSmsQueue
            - Arn
          Action: "SQS:SendMessage"
          Condition:
            ArnEquals:
              "aws:SourceArn": !Ref SendTextSnsTopic
    Queues:
      - Ref: SendTextSmsQueue

SendTextSmsQueueSubscription:
  Type: AWS::SNS::Subscription
  Properties:
    TopicArn: !Ref SendTextSnsTopic
    Endpoint: !GetAtt
      - SendTextSmsQueue
      - Arn
    Protocol: sqs
    RawMessageDelivery: true
